version: "2"
run:
  issues-exit-code: 1
linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - gocritic
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - sloglint
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unused
    - whitespace
  settings:
    errcheck:
      check-type-assertions: false
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - rangeValCopy
        - hugeParam
        - paramTypeCombine
        - tooManyResultsChecker
        - unnamedResult
    nolintlint:
      require-explanation: true
      require-specific: true
    sloglint:
      no-mixed-args: true
      kv-only: false
      attr-only: true
      context: scope
      static-msg: true
      key-naming-case: snake
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
