//go:build !windows

package opencode

import "strings"

// sessionCarrierShellWrapperTemplate is the shell OpenCode is pointed at in
// place of a login shell.
//
// OpenCode starts bash and zsh with -l and then sources the user's startup
// files, so a search path handed over in the environment is rewritten before
// the command runs: macOS path_helper hoists the system directories and a
// startup file is free to prepend anything else. The wrapper reproduces that
// same startup sequence and only then puts the addressed session's directories
// in front, so the order the command resolves against is the order the session
// asked for.
//
// The reproduced sequence is OpenCode's own, argument for argument: zsh gets
// "-l -c" with ~/.zshenv and "${ZDOTDIR:-$HOME}/.zshrc" sourced, bash gets
// "-l -c" with expand_aliases and ~/.bashrc, and both then cd to the operation
// directory and eval the command. An operation that carries no directories
// therefore runs exactly what OpenCode would have run, startup files included,
// on the very shell OpenCode would have started.
//
// Nothing of what the wrapper needs travels in an environment variable of the
// adapter's own, and nothing of it is held anywhere the runtime as a whole can
// reach. Both halves arrive with the operation, around one addressed region of
// the search path: the operation's directories in front of it, and the login
// shell that this operation's workspace scope resolved inside it. The wrapper
// removes the whole region from the search path before the login shell starts
// and hands the directories to the login sequence as a positional argument, so
// nothing the adapter owns is left in the environment the user's command runs
// under.
//
// The region is counted, not delimited. ':' is a legal character in a POSIX
// executable path, so a shell path written as one search-path component cannot
// be read back: '/opt/a:b/zsh' would truncate to '/opt/a'. The address is
// therefore the marker, the number of segments the shell path splits into, and
// those segments in order, with the runtime's own path always following as the
// final component so the last segment is always terminated. Reading back
// exactly that many segments and rejoining them reproduces every path OpenCode
// itself accepts, separators and all, with no escaping to get wrong.
//
// The wrapper fails closed. An operation that published no marker published no
// shell, and a wrapper that guessed one would be answering for a workspace
// scope that never spoke — which is exactly how a runtime-wide shell serves one
// scope's login shell to another scope's session. An address that is present
// but not well formed — an unterminated or non-canonical count, or fewer
// segments than it claims — is refused on the same ground: it names no shell
// this operation can be shown to have asked for.
//
// The one placeholder is replaced with a quoted absolute path; the template is
// not a format string, because the parameter expansions below are full of
// percent signs that mean removal patterns rather than verbs.
const sessionCarrierShellWrapperTemplate = `#!/bin/sh
# Generated by acp-go-opencode. OpenCode invokes an unrecognised shell as
# "<shell> -c <command>", which is the only form this wrapper rewrites.
carrier_mark=@CARRIER_MARK@

carrier_refuse() {
	printf 'acp-go-opencode session carrier: %s\n' "$1" >&2
	exit 127
}

carrier_dirs=${PATH%%"$carrier_mark":*}
[ "$carrier_dirs" != "$PATH" ] || carrier_refuse 'this operation published no login shell'

carrier_rest=${PATH#*"$carrier_mark":}
carrier_dirs=${carrier_dirs%:}

# The segment count, terminated by the separator that begins the first segment.
case "$carrier_rest" in
*:*) ;;
*) carrier_refuse 'this operation published a malformed login-shell address' ;;
esac

carrier_count=${carrier_rest%%:*}
carrier_rest=${carrier_rest#*:}

# One canonical spelling only: decimal digits, at least one segment, no leading
# zero, and short enough to be an integer this shell can compare.
case "$carrier_count" in
''|0*|*[!0123456789]*) carrier_refuse 'this operation published a malformed login-shell address' ;;
esac
[ "${#carrier_count}" -le 9 ] || carrier_refuse 'this operation published a malformed login-shell address'

carrier_shell=
carrier_taken=0

while [ "$carrier_taken" -lt "$carrier_count" ]; do
	case "$carrier_rest" in
	*:*) ;;
	*) carrier_refuse 'this operation published a truncated login-shell address' ;;
	esac

	carrier_segment=${carrier_rest%%:*}
	carrier_rest=${carrier_rest#*:}

	if [ "$carrier_taken" -eq 0 ]; then
		carrier_shell=$carrier_segment
	else
		carrier_shell=$carrier_shell:$carrier_segment
	fi

	carrier_taken=$((carrier_taken + 1))
done

if [ -n "$carrier_dirs" ] && [ -n "$carrier_rest" ]; then
	PATH=$carrier_dirs:$carrier_rest
else
	PATH=$carrier_dirs$carrier_rest
fi
export PATH

[ -x "$carrier_shell" ] || carrier_refuse 'this operation named no runnable login shell'
[ "$#" -eq 2 ] && [ "$1" = "-c" ] || carrier_refuse 'OpenCode invoked this shell in a form it does not stand in for'

case "${carrier_shell##*/}" in
zsh)
	exec "$carrier_shell" -l -c '
		[ -f "$HOME/.zshenv" ] && . "$HOME/.zshenv" >/dev/null 2>&1
		[ -f "${ZDOTDIR:-$HOME}/.zshrc" ] && . "${ZDOTDIR:-$HOME}/.zshrc" >/dev/null 2>&1
		cd -- "$1" || exit 1
		[ -n "$3" ] && PATH=$3:$PATH
		eval "$2"
	' opencode "$PWD" "$2" "$carrier_dirs"
	;;
bash)
	exec "$carrier_shell" -l -c '
		shopt -s expand_aliases
		[ -f "$HOME/.bashrc" ] && . "$HOME/.bashrc" >/dev/null 2>&1
		cd -- "$1" || exit 1
		[ -n "$3" ] && PATH=$3:$PATH
		eval "$2"
	' opencode "$PWD" "$2" "$carrier_dirs"
	;;
esac

carrier_refuse 'this operation named a login shell the wrapper does not reproduce'
`

func sessionCarrierShellWrapperSource(pathMark string) string {
	return strings.NewReplacer(
		"@CARRIER_MARK@", shellStringLiteral(pathMark),
	).Replace(sessionCarrierShellWrapperTemplate)
}

// shellStringLiteral renders a value as a single-quoted POSIX shell word, which
// quotes everything a generated path can hold including a single quote of its
// own.
func shellStringLiteral(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
